<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Students [
    <!ELEMENT Students (Student+)>

    <!ELEMENT Student (ID, Name, Mathematics, English, IT)>

    <!ELEMENT ID (#PCDATA)>
    <!ELEMENT Name (#PCDATA)>

    <!ELEMENT Mathematics (Test1, MathTest2)>
    <!ELEMENT Test1 (#PCDATA)>
    <!ELEMENT MathTest2 (#PCDATA)>

    <!ELEMENT English (Essay1, Essay2)>
    <!ELEMENT Essay1 (#PCDATA)>
    <!ELEMENT Essay2 (#PCDATA)>

    <!ELEMENT IT (Activity1, ITTest2, Essay3)>
    <!ELEMENT Activity1 (#PCDATA)>
    <!ELEMENT ITTest2 (#PCDATA)>
    <!ELEMENT Essay3 (#PCDATA)>
]>

<Students>
    <Student>
        <ID>16430122-1521</ID>
        <Name>Pace, Camden G.</Name>
        <Mathematics>
            <Test1>54%</Test1>
            <MathTest2>63%</MathTest2>
        </Mathematics>
        <English>
            <Essay1>C+</Essay1>
            <Essay2>B+</Essay2>
        </English>
        <IT>
            <Activity1>Pass</Activity1>
            <ITTest2>32%</ITTest2>
            <Essay3>C+</Essay3>
        </IT>
    </Student>
    <Student>
        <ID>16470212-9851</ID>
        <Name>Weber, Lucy X.</Name>
        <Mathematics>
            <Test1>32%</Test1>
            <MathTest2>41%</MathTest2>
        </Mathematics>
        <English>
            <Essay1>C-</Essay1>
            <Essay2>C-</Essay2>
        </English>
        <IT>
            <Activity1>Fail</Activity1>
            <ITTest2>73%</ITTest2>
            <Essay3>D+</Essay3>
        </IT>
    </Student>
    <Student>
        <ID>16060213-9990</ID>
        <Name>Branch, Caesar A.</Name>
        <Mathematics>
            <Test1>73%</Test1>
            <MathTest2>81%</MathTest2>
        </Mathematics>
        <English>
            <Essay1>C-</Essay1>
            <Essay2>C+</Essay2>
        </English>
        <IT>
            <Activity1>Pass</Activity1>
            <ITTest2>63%</ITTest2>
            <Essay3>B+</Essay3>
        </IT>
    </Student>
    <Student>
        <ID>16720905-9422</ID>
        <Name>Beck, Sara K.</Name>
        <Mathematics>
            <Test1>66%</Test1>
            <MathTest2>57%</MathTest2>
        </Mathematics>
        <English>
            <Essay1>C-</Essay1>
            <Essay2>D+</Essay2>
        </English>
        <IT>
            <Activity1>Pass</Activity1>
            <ITTest2>41%</ITTest2>
            <Essay3>C-</Essay3>
        </IT>
    </Student>
    <Student>
        <ID>16471011-5884</ID>
        <Name>Valenzuela, Daphne E.</Name>
        <Mathematics>
            <Test1>43%</Test1>
            <MathTest2>45%</MathTest2>
        </Mathematics>
        <English>
            <Essay1>B+</Essay1>
            <Essay2>A-</Essay2>
        </English>
        <IT>
            <Activity1>Fail</Activity1>
            <ITTest2>63%</ITTest2>
            <Essay3>C-</Essay3>
        </IT>
    </Student>
</Students>
